version: '2'
services:
  redis:
    image: "redis:alpine"
  backend:
    build: ./server
    ports:
     - "4000:3000"
    volumes:
     - ./server:/app
     - /app/node_modules
     - ./wait_for_it.sh:/app/wait_for_it.sh
    depends_on:
      - redis
    command: ["node", "server.js"]
  frontend:
    build: ./client
    ports:
     - "3000:3000"
     - "35729:35729"
    volumes:
     - ./client:/app
     - /app/node_modules
     - ./wait_for_it.sh:/app/wait_for_it.sh
    depends_on:
      - backend
    command: ["npm", "start"]
